version: '3.8'

name: llm-zoomcamp-workspace
services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: llm-zoomcamp-workspace
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached

  elasticsearch:
    container_name: elasticsearch-llm
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - LICENSE=basic
    volumes:
      - elasticsearch-llm-data:/usr/share/elasticsearch/data

networks:
  default:
    name: llm-zoomcamp-network

volumes:
  elasticsearch-llm-data: